// NAGU menu data — canonical lineup. Prices in SR.
// Photography: assets/products/* (from the "NAGU Menu Shots" set).
// Nutrition fields (calories / ingredients / allergens) are representative
// placeholders for the storefront — swap for lab-verified values before launch.
// Homepage Lineup shows only the "Burgers"; the Menu page shows everything.
window.NAGU_MENU = {
  categories: ["Burgers", "Sides", "Full Menu"],
  items: [
    {
      id: "old-school-double-smash",
      cat: "Burgers",
      name: "Old School Double Smash",
      tagline: "Classic, cheesy, satisfying.",
      desc: "Two smashed beef patties, melted cheese, pickles and NAGU sauce on a toasted brioche bun.",
      price: 22,
      calories: 740,
      ingredients: "Smashed beef, cheddar, pickles, onion, NAGU sauce, brioche bun.",
      allergies: "Gluten, dairy, egg, sesame.",
      image: "../../assets/products/old-school-double-smash.png",
      tags: ["Comfort Classic", "Beef"],
      hero: true,
    },
    {
      id: "tokyo-drift-double-smash",
      cat: "Burgers",
      name: "Tokyo Drift Double Smash",
      tagline: "Double beef, Tokyo heat.",
      desc: "Double smashed beef, spicy Tokyo glaze, melted cheese and crisp pickles. Built loud.",
      price: 26,
      calories: 820,
      ingredients: "Smashed beef, Tokyo chili glaze, cheese, pickles, brioche bun.",
      allergies: "Gluten, dairy, egg, soy, sesame.",
      image: "../../assets/products/tokyo-drift-double-smash.png",
      tags: ["Asian Twist", "Spicy"],
    },
    {
      id: "gochujang-crispy-chicken",
      cat: "Burgers",
      name: "Gochujang Crispy Chicken",
      tagline: "Crispy, saucy, craveable.",
      desc: "Double-fried chicken thigh, gochujang glaze and slaw on a toasted bun. Crunch you can hear.",
      price: 24,
      calories: 700,
      ingredients: "Fried chicken thigh, gochujang glaze, slaw, brioche bun.",
      allergies: "Gluten, egg, soy, sesame.",
      image: "../../assets/products/gochujang-crispy-chicken.png",
      tags: ["Crispy Crunch", "Chicken"],
    },
    {
      id: "seasoned-nagu-fries",
      cat: "Sides",
      name: "Seasoned NAGU Fries",
      tagline: "Crisp. Seasoned. Classic.",
      desc: "Golden fries tossed in NAGU's signature seasoning. The one you always add.",
      price: 12,
      calories: 360,
      ingredients: "Potato, sunflower oil, NAGU seasoning.",
      allergies: "May contain traces of gluten. Shared fryer.",
      image: "../../assets/products/seasoned-nagu-fries.png",
      tags: ["Classic"],
    },
    {
      id: "loaded-kimchi-fries",
      cat: "Sides",
      name: "Loaded Kimchi Fries",
      tagline: "Piled, saucy, shareable.",
      desc: "Fries loaded with kimchi, melted cheese, sauce and crunch. Made to share — or not.",
      price: 18,
      calories: 560,
      ingredients: "Fries, kimchi, melted cheese, NAGU sauce, scallion.",
      allergies: "Gluten, dairy, soy.",
      image: "../../assets/products/loaded-kimchi-fries.png",
      tags: ["Shareable Hit", "Spicy"],
    },
    {
      id: "kendo-chicken-bites",
      cat: "Sides",
      name: "Kendo Chicken Bites",
      tagline: "Bite-size. Big crunch.",
      desc: "Crispy popcorn-style chicken bites with dipping sauce. High-repeat snack.",
      price: 15,
      calories: 420,
      ingredients: "Chicken breast, crisp batter, dipping sauce.",
      allergies: "Gluten, egg, soy.",
      image: "../../assets/products/kendo-chicken-bites.png",
      tags: ["Crispy Crunch", "Chicken"],
    },
    {
      id: "sriracha-glazed-shrimps",
      cat: "Sides",
      name: "Sriracha Glazed Shrimps",
      tagline: "Sweet heat, crispy shell.",
      desc: "Crispy shrimp tossed in a sweet sriracha-honey glaze. Bring the heat.",
      price: 28,
      calories: 480,
      ingredients: "Shrimp, crisp batter, sriracha-honey glaze, sesame.",
      allergies: "Shellfish, gluten, egg, soy, sesame.",
      image: "../../assets/products/sriracha-glazed-shrimps.png",
      tags: ["Spicy", "Seafood"],
    },
    {
      id: "full-menu",
      cat: "Full Menu",
      name: "Full Menu Arranged",
      tagline: "The whole lineup. One order.",
      desc: "Every burger and every side — the complete NAGU spread in a single order. Built to feed the whole crew.",
      price: 200,
      ingredients: "The full NAGU lineup: all burgers + all sides.",
      allergies: "Contains all menu allergens: gluten, dairy, egg, soy, sesame, shellfish.",
      image: "../../assets/products/full-menu.png",
      tags: ["Best Value", "Feeds the Crew"],
    },
  ],
};
